# Generated by Django 5.0.6 on 2024-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
